### ISSUE TITLE
Jibcon 앱 개선점

### ISSUE THREAD

**Issue by bigstark** [Jibcon/jibcon_android#41]
써놨던게 사라져서 다시 정리했습니다. 
다시 정리한만큼 내용이 부족할 수 있습니다! 생각날 때마다 계속 작성해볼게요!

## Application

- [x] Jibcon 은 많은 라이브러리를 사용하고있기 때문에 Multidex 설정이 필요합니다. 
- [x] Activity instance 는 절대로 가지고 있으면 안됩니다.
`private static volatile Activity currentActivity = null;`
만약에 필요하다면 WeakReference 형태로 가지고있어야 합니다.
- [x] static 메소드는 넣지 않는 편이 좋습니다.

## Coding Convention 

- [x] package 는 보통 소문자, class 는 보통 대문자로 네이밍을 합니다. (class / package 구분을 위함)
- [x] class 의 네이밍은 보통 CamelCase 스타일로 합니다.
- [x] 변수의 네이밍도 통일해주세요.
- [x] xml의 네이밍은 보통 under_score 스타일로 합니다. 
- [x] layout 의 네이밍이 통일성이 있어야 합니다.
- [x] Activity / Fragment / Adapter / ViewHolder 등 류의 것들은 구분이 잘 되도록 네이밍을 해주세요.
- [x] 중괄호 / 괄호 등에 대한 것에 대해서도 공통된 폼이 필요합니다.

## XML

- [ ] strings / dimens / colors 는 꼭 정의해서 사용해주세요.
- [ ] drawable directory 에는 image 파일을 넣지 않는 편이 좋습니다. 보통 selector / shape / vector image / - [ ]ayer-list 등만 넣는 편입니다. (다양한 화면 크기 대응이 되지 않습니다.)

## Code

- [x] Inner Class 는 사용하지 않는 편이 좋습니다.
- [ ] 변수에 접근제어자를 설정하는 습관을 들이시는게 좋습니다. (private 과 public 으로 가볍게 시작해보세요!) 
- [x] Activity 혹은 Fragment 에 공통적으로 사용하는 코드가 있다면 상속을 사용해보시는 편이 좋습니다.
(보통 BaseActivity 를 하나 생성하고 공통코드를 넣어두는 편입니다.)
- [x] 고정된 String 을 사용할 때는 static final 를 사용하여 메모리 할당을 한번만 하도록 해주세요.
- [x] API 와 관련된 부분은 GC가 되지 않을 때가 많습니다. gson 도 마찬가지입니다. singleton 으로 처리하거나 캐싱하여 처리해주세요.

**Comment by kujyp** [comment]
Coding Convention - 변수의 네이밍도 통일해주세요.

아래대로 통일할게요
https://source.android.com/source/code-style#follow-field-naming-conventions
![image](https://user-images.githubusercontent.com/19223089/27367505-621d8ee8-5688-11e7-8d71-bb420e527026.png)

**Comment by kujyp** [comment]
mSidebarConnectedDevicesLV ->
mSidebarConnectedDevicesLv
FAQ ->
Faq
약어 대문자로 쓰지말아주세요. constant랑 해깔립니다. 

멤버변수아닌것에 m붙이말아주세요
void onCreate() {...
ImageView mImageView = ...
mImageView.setOnClickListener(... ->

ImageView imageView = ...
imageView.setOnClickListener(...
}

필드 변수명
skip_button->
mSkipButton
underscore, carmel 혼재하지말아주세요 

int MAX_PAGE = 4->
int mMaxPage = 4
상수로 쓸거면 constant로 이동 or final

**Comment by kujyp** [comment]
**현재까지 진행상상황입니당**

![20170709_143243](https://user-images.githubusercontent.com/19223089/27991504-15110622-64b4-11e7-9bb0-da792ce76cd9.png)

**Comment by bigstark** [comment]
제가 checkbox로 바꿔드릴테니 체크하셔요 ㅎㅎㅎ

**Comment by kujyp** [comment]
@bigstark 오.. 고맙습니다 ㅋㅋ

**Comment by kujyp** [comment]
@ZZANZU @94imain @Nickping  Commit Message에 #issuenumber 써주세요

**Comment by kujyp** [comment]
@Nickping @94imain @Nickping 그리고 본인이 한거 맨위에 체크박스 체크해주세요

**Comment by kujyp** [comment]
XML - 2개는 추후에 하기로.
1. strings / dimens / colors 는 꼭 정의해서 사용해주세요.
2. drawable directory 에는 image 파일을 넣지 않는 편이 좋습니다. 보통 selector / shape / vector image / - [ ]ayer-list 등만 넣는 편입니다. (다양한 화면 크기 대응이 되지 않습니다.)
