### ISSUE TITLE
Layout Naming 방법 정의 #41

### ISSUE THREAD

**Issue by ZZANZU** [Jibcon/jibcon_android#57]
# Before : 
구성요소_설명.xml 
ex. activity_adddevice.xml , content_main.xml

# After : 
화면단위_설명_구성요소.xml 
ex. cheatkey_active_fragment.xml, conshop_market_menu.xml

**Comment by kujyp** [comment]
Jul 12 16:30 Review 결과

1.
Package_Description_Component.xml(화면단위_설명_구성요소.xml)
->
Package_Javafilename_Component_(Description) (여러개일경우만)

2. 
Package가 없는 Component의 경우 명명이 힘들었음.
ex) MainActivity.java
->
main 패키지를 생성하자

3. 
여러 Java파일에서 사용되는 리소스? -> Multiuse를 넣자.
