### ISSUE TITLE
TutorialFragment의 코드중복

### ISSUE THREAD

**Issue by 94imain** [Jibcon/jibcon_android#61]
같은코드가4개가 중복돼서, 간소화작업이 필요해 보입니다.

**Comment by kujyp** [comment]
strings.xml에 있는 string1 2 3 4도 string-array로 바꾸면 좋을것같습니다.

https://github.com/Jibcon/jibcon_android_jyp/blob/master/app/src/main/res/values/tutorials.xml

#68
