### ISSUE TITLE
app_design_refacor

### ISSUE THREAD

**Issue by ZZANZU** [Jibcon/jibcon_android#63]
Application의 조잡함 제거

- [x] 1. X모양 이미지
- [x] 2. 로그인 후 액티비티의 skip버튼 (개발자용)

     ![image](https://user-images.githubusercontent.com/26498433/28149950-5fc7b952-67cc-11e7-8b1a-0324dedac5b3.png)

- [x] 3. '나의 집콘 만들기' & '다른 집콘 초대받기'의 (상단 화살표)와 (액티비티 이름) 화면 배치
  - 마진값/패딩값 조정

     ![image](https://user-images.githubusercontent.com/26498433/28148121-d27e3ad2-67bf-11e7-8000-886748e1f4f5.png)

- [x] 4. 초기 화면의 메뉴 활성화 버튼이 4번째가 기본으로 되어있음(첫번째가 기본이 되어야)

    ![image](https://user-images.githubusercontent.com/26498433/28148343-0ac498d6-67c1-11e7-9819-881e8c4b5be7.png)

- [ ] 5. 등록 기기 카드뷰의 크기가 일정하지 않음

     ![image](https://user-images.githubusercontent.com/26498433/28148375-42477e2c-67c1-11e7-8666-3635baae3292.png)

- [ ] 6. Login화면에서 여러 가입버튼의 크기 통일화 , 샘플계정으로 들어가기의 버튼은 바탕이 투명색으로 고치기!

- [x] 7. Login video 수정, splash이미지 임시적용 - 디자이너면접용으로 임시로라도 적용시켜야할것같습니다!

**Comment by kujyp** [comment]
2. 로그인 후 액티비티의 skip버튼 (개발자용)
-> 개발자 전용이라면 안보이게 해놓은담에 그냥 클릭되도록 하면 될거같아요.

나머지는 굿

**Comment by kujyp** [comment]
디자인 변경 될것같으므로 일단 종료
