### ISSUE TITLE
메인화면 (DeviceFragment)에서 아이콘배치 레이아웃 관련 #64

### ISSUE THREAD

**Issue by Nickping** [Jibcon/jibcon_android#64]
밑으로 내리면 내릴수록 끝없이 내려갑니다. 
처음 코딩할때 GridView상속받아서 myGridView로 적용했는데
나름대로 만든 뷰라서 에러가 있는것 같습니다

리사이클러뷰로 적용하는게 나을듯 합니다

**Comment by ZZANZU** [comment]
치트키 파트에서 구현한 방법을 적용해보는 것은 어떨까요?

**Comment by kujyp** [comment]
좋습니다.
