### ISSUE TITLE
Thread-safe Singleton 적용

### ISSUE THREAD

**Issue by kujyp** [Jibcon/jibcon_android#95]
```
public static Singleton getInstance() {
        if (instance == null) {
            synchronized(Singleton.class) {
                if (instance == null) {
                    instance = new Singleton();
                }
            }
        }
        return instance;
    }
}
```

**Comment by ZZANZU** [comment]
public class RetrofiClients {
    private static RetrofiClients sInstance;

    private HashMap<Class, Object> services = new HashMap<>();

    public static RetrofiClients getInstance() {
        if (sInstance == null) {
            synchronized(RetrofiClients.class) {
                if (sInstance == null) {
                    sInstance = new RetrofiClients();
                }
            }
        }
        return sInstance;
    }
(중략)

위와 같은 상황에서 RetrofitClient 클래스는 아무것도 implement하지 않는데도 synchronized를 해야하는 것인가요?
